// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: Worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_Worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_Worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RegisterResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetBuildingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerUuid    string                 `protobuf:"bytes,1,opt,name=worker_uuid,json=workerUuid,proto3" json:"worker_uuid,omitempty"`
	WorkerKey     string                 `protobuf:"bytes,2,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildingRequest) Reset() {
	*x = GetBuildingRequest{}
	mi := &file_Worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingRequest) ProtoMessage() {}

func (x *GetBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingRequest.ProtoReflect.Descriptor instead.
func (*GetBuildingRequest) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{2}
}

func (x *GetBuildingRequest) GetWorkerUuid() string {
	if x != nil {
		return x.WorkerUuid
	}
	return ""
}

func (x *GetBuildingRequest) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

type GetBuildingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	UnixTime      uint64                 `protobuf:"varint,4,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildingResponse) Reset() {
	*x = GetBuildingResponse{}
	mi := &file_Worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingResponse) ProtoMessage() {}

func (x *GetBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingResponse.ProtoReflect.Descriptor instead.
func (*GetBuildingResponse) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{3}
}

func (x *GetBuildingResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetBuildingResponse) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *GetBuildingResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *GetBuildingResponse) GetUnixTime() uint64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	UnixTime      uint64                 `protobuf:"varint,3,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_Worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteTaskRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CompleteTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CompleteTaskRequest) GetUnixTime() uint64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_Worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_Worker_proto protoreflect.FileDescriptor

const file_Worker_proto_rawDesc = "" +
	"\n" +
	"\fWorker.proto\x12\x06worker\"%\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\tR\x04auth\"8\n" +
	"\x10RegisterResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"T\n" +
	"\x12GetBuildingRequest\x12\x1f\n" +
	"\vworker_uuid\x18\x01 \x01(\tR\n" +
	"workerUuid\x12\x1d\n" +
	"\n" +
	"worker_key\x18\x02 \x01(\tR\tworkerKey\"t\n" +
	"\x13GetBuildingResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1b\n" +
	"\tunix_time\x18\x04 \x01(\x04R\bunixTime\"`\n" +
	"\x13CompleteTaskRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1b\n" +
	"\tunix_time\x18\x03 \x01(\x04R\bunixTime\"&\n" +
	"\x14CompleteTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xe7\x01\n" +
	"\rWorkerService\x12C\n" +
	"\x0eRegisterWorker\x12\x17.worker.RegisterRequest\x1a\x18.worker.RegisterResponse\x12F\n" +
	"\vGetBuilding\x12\x1a.worker.GetBuildingRequest\x1a\x1b.worker.GetBuildingResponse\x12I\n" +
	"\fCompleteTask\x12\x1b.worker.CompleteTaskRequest\x1a\x1c.worker.CompleteTaskResponseB+Z)github.com/nrf24l01/cp_money_contoller/pbb\x06proto3"

var (
	file_Worker_proto_rawDescOnce sync.Once
	file_Worker_proto_rawDescData []byte
)

func file_Worker_proto_rawDescGZIP() []byte {
	file_Worker_proto_rawDescOnce.Do(func() {
		file_Worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Worker_proto_rawDesc), len(file_Worker_proto_rawDesc)))
	})
	return file_Worker_proto_rawDescData
}

var file_Worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Worker_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: worker.RegisterRequest
	(*RegisterResponse)(nil),     // 1: worker.RegisterResponse
	(*GetBuildingRequest)(nil),   // 2: worker.GetBuildingRequest
	(*GetBuildingResponse)(nil),  // 3: worker.GetBuildingResponse
	(*CompleteTaskRequest)(nil),  // 4: worker.CompleteTaskRequest
	(*CompleteTaskResponse)(nil), // 5: worker.CompleteTaskResponse
}
var file_Worker_proto_depIdxs = []int32{
	0, // 0: worker.WorkerService.RegisterWorker:input_type -> worker.RegisterRequest
	2, // 1: worker.WorkerService.GetBuilding:input_type -> worker.GetBuildingRequest
	4, // 2: worker.WorkerService.CompleteTask:input_type -> worker.CompleteTaskRequest
	1, // 3: worker.WorkerService.RegisterWorker:output_type -> worker.RegisterResponse
	3, // 4: worker.WorkerService.GetBuilding:output_type -> worker.GetBuildingResponse
	5, // 5: worker.WorkerService.CompleteTask:output_type -> worker.CompleteTaskResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Worker_proto_init() }
func file_Worker_proto_init() {
	if File_Worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Worker_proto_rawDesc), len(file_Worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Worker_proto_goTypes,
		DependencyIndexes: file_Worker_proto_depIdxs,
		MessageInfos:      file_Worker_proto_msgTypes,
	}.Build()
	File_Worker_proto = out.File
	file_Worker_proto_goTypes = nil
	file_Worker_proto_depIdxs = nil
}
