// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: Worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_Worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Id            uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_Worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RegisterResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RegisterResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerUuid    string                 `protobuf:"bytes,1,opt,name=worker_uuid,json=workerUuid,proto3" json:"worker_uuid,omitempty"`
	WorkerKey     string                 `protobuf:"bytes,2,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_Worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetWorkerUuid() string {
	if x != nil {
		return x.WorkerUuid
	}
	return ""
}

func (x *GetTaskRequest) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	UnixTime      uint64                 `protobuf:"varint,4,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_Worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetTaskResponse) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *GetTaskResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *GetTaskResponse) GetUnixTime() uint64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type ChangeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Logs          string                 `protobuf:"bytes,3,opt,name=logs,proto3" json:"logs,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	UnixTime      uint64                 `protobuf:"varint,5,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStatusRequest) Reset() {
	*x = ChangeStatusRequest{}
	mi := &file_Worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusRequest) ProtoMessage() {}

func (x *ChangeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeStatusRequest) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeStatusRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChangeStatusRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ChangeStatusRequest) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *ChangeStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChangeStatusRequest) GetUnixTime() uint64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type ChangeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStatusResponse) Reset() {
	*x = ChangeStatusResponse{}
	mi := &file_Worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusResponse) ProtoMessage() {}

func (x *ChangeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusResponse.ProtoReflect.Descriptor instead.
func (*ChangeStatusResponse) Descriptor() ([]byte, []int) {
	return file_Worker_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeStatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_Worker_proto protoreflect.FileDescriptor

const file_Worker_proto_rawDesc = "" +
	"\n" +
	"\fWorker.proto\x12\x06worker\"!\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"H\n" +
	"\x10RegisterResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\"P\n" +
	"\x0eGetTaskRequest\x12\x1f\n" +
	"\vworker_uuid\x18\x01 \x01(\tR\n" +
	"workerUuid\x12\x1d\n" +
	"\n" +
	"worker_key\x18\x02 \x01(\tR\tworkerKey\"p\n" +
	"\x0fGetTaskResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1b\n" +
	"\tunix_time\x18\x04 \x01(\x04R\bunixTime\"\x8c\x01\n" +
	"\x13ChangeStatusRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x12\n" +
	"\x04logs\x18\x03 \x01(\tR\x04logs\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tunix_time\x18\x05 \x01(\x04R\bunixTime\"&\n" +
	"\x14ChangeStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xdb\x01\n" +
	"\rWorkerService\x12C\n" +
	"\x0eRegisterWorker\x12\x17.worker.RegisterRequest\x1a\x18.worker.RegisterResponse\x12:\n" +
	"\aGetTask\x12\x16.worker.GetTaskRequest\x1a\x17.worker.GetTaskResponse\x12I\n" +
	"\fChangeStatus\x12\x1b.worker.ChangeStatusRequest\x1a\x1c.worker.ChangeStatusResponseB+Z)github.com/nrf24l01/cp_money_contoller/pbb\x06proto3"

var (
	file_Worker_proto_rawDescOnce sync.Once
	file_Worker_proto_rawDescData []byte
)

func file_Worker_proto_rawDescGZIP() []byte {
	file_Worker_proto_rawDescOnce.Do(func() {
		file_Worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Worker_proto_rawDesc), len(file_Worker_proto_rawDesc)))
	})
	return file_Worker_proto_rawDescData
}

var file_Worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Worker_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: worker.RegisterRequest
	(*RegisterResponse)(nil),     // 1: worker.RegisterResponse
	(*GetTaskRequest)(nil),       // 2: worker.GetTaskRequest
	(*GetTaskResponse)(nil),      // 3: worker.GetTaskResponse
	(*ChangeStatusRequest)(nil),  // 4: worker.ChangeStatusRequest
	(*ChangeStatusResponse)(nil), // 5: worker.ChangeStatusResponse
}
var file_Worker_proto_depIdxs = []int32{
	0, // 0: worker.WorkerService.RegisterWorker:input_type -> worker.RegisterRequest
	2, // 1: worker.WorkerService.GetTask:input_type -> worker.GetTaskRequest
	4, // 2: worker.WorkerService.ChangeStatus:input_type -> worker.ChangeStatusRequest
	1, // 3: worker.WorkerService.RegisterWorker:output_type -> worker.RegisterResponse
	3, // 4: worker.WorkerService.GetTask:output_type -> worker.GetTaskResponse
	5, // 5: worker.WorkerService.ChangeStatus:output_type -> worker.ChangeStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Worker_proto_init() }
func file_Worker_proto_init() {
	if File_Worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Worker_proto_rawDesc), len(file_Worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Worker_proto_goTypes,
		DependencyIndexes: file_Worker_proto_depIdxs,
		MessageInfos:      file_Worker_proto_msgTypes,
	}.Build()
	File_Worker_proto = out.File
	file_Worker_proto_goTypes = nil
	file_Worker_proto_depIdxs = nil
}
