@startuml Архитектура
package "Worker" {
    [Selenium] <- [Python обёртка]
}

package "Core" {
    [Серв] <-> http
    [Python обёртка] ..> http : REST API
}

package "RabbitMQ" {
    [Python обёртка] <.. RabbitMQ : Задание взято 
    [Серв] ..> RabbitMQ : Задание
    note right of [RabbitMQ]
        Очередь заданий и результатов
    end note
}

package "Cli" {
    [cli] ..> http : Управляющие запросы
    note right of [cli]
        Управление пользователем через консоль
    end note
}

package "Frontend" {
    [Front] ..> http : управляющие запросы
    note right of [Front]
        Управление системой через vue.js на фронте
    end note
}
@enduml